# You can remove this top line to fix the obsolete version warning
version: '3.8'

services:
  # Go API Service
  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKER: kafka:29092
      KAFKA_TOPIC: activities
      # The ClickHouse address for the Go driver
      CLICKHOUSE_ADDR: clickhouse:9000
    depends_on:
      - kafka
      - clickhouse

  # Go Worker Service
  worker:
    build: ./worker
    environment:
      KAFKA_BROKER: kafka:29092
      KAFKA_TOPIC: activities
      # The ClickHouse address for the Go driver
      CLICKHOUSE_ADDR: clickhouse:9000
    depends_on:
      - kafka
      - clickhouse

  # ClickHouse OLAP Database
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native client interface
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ulimits: # Recommended settings for ClickHouse
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  # Kafka Message Broker
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  # Zookeeper (required by Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

volumes:
  clickhouse-data: