apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: streamtrack
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80 # Public port
    targetPort: 8080 # Container port